package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// cmdShellInit prints a shell snippet that prevents the shell from
// expanding glob characters (`?`, `*`, `[`, `]`, `{`, `}`) in
// natural-language prompts before they reach our binary.
//
// This is a real problem in zsh, where the default NOMATCH option
// makes `i is google's dns up?` fail with "no matches found: up?"
// without ever invoking us. Bash and fish are mostly fine by default
// but get the same treatment for users who've turned on stricter glob
// behavior (`shopt -s failglob`, etc.).
//
// Usage:
//
//	eval "$(i shell-init zsh)"
//	eval "$(i shell-init bash)"
//	i shell-init fish | source
//
// Implementation note: glob expansion happens during command-line
// parsing — before any function body would run. So we can't fix this
// from inside a function. The trick is to use a shell construct that
// runs *before* glob expansion. In zsh that's the `noglob` precommand
// modifier delivered via an alias (aliases are expanded earlier than
// globs). In bash we use `set -f` wrapped around the command via an
// alias for the same reason. In fish we use a function with `set -l
// argv` because fish doesn't glob `?` and only globs `*` strictly.
func cmdShellInit(_ context.Context, args []string) int {
	shell := ""
	if len(args) > 0 {
		shell = strings.ToLower(args[0])
	}
	if shell == "" {
		shell = detectParentShell()
	}
	switch shell {
	case "zsh":
		fmt.Print(zshSnippet)
		return 0
	case "bash":
		fmt.Print(bashSnippet)
		return 0
	case "fish":
		fmt.Print(fishSnippet)
		return 0
	default:
		errf("shell-init: unsupported or unknown shell %q (try: zsh | bash | fish)", shell)
		return 2
	}
}

func detectParentShell() string {
	if v := os.Getenv("SHELL"); v != "" {
		return strings.ToLower(filepath.Base(v))
	}
	return ""
}

// zshSnippet uses zsh's `noglob` precommand modifier. Aliases in zsh
// are expanded before glob expansion, so wrapping `i` with `noglob i`
// suppresses globbing of the trailing words for that one command.
// This is the canonical zsh fix; it doesn't touch any global option.
//
// Known limitation: zsh tokenises the command line *before* alias
// expansion, so apostrophes / single quotes in unquoted input still
// cause a shell parse error ("unmatched '"). This cannot be fixed at
// the alias or function level; wrap such prompts in double quotes:
//
//	i "what's the status"   ← works
//	i what's the status     ← zsh parse error (unmatched ')
const zshSnippet = `# intent shell integration — generated by ` + "`i shell-init zsh`" + `
# Wraps i / intent with zsh's ` + "`noglob`" + ` precommand modifier so that
# natural-language prompts containing ? * [ ] { } don't get expanded
# (or rejected as NOMATCH) by zsh before they reach intent.
#
# Add to ~/.zshrc:   eval "$(intent shell-init zsh)"
#
# ── Apostrophe / single-quote limitation ──────────────────────────────
# zsh tokenises the command line *before* this alias fires.  Inputs that
# contain an apostrophe or single quote (don't, it's, Google's) will
# trigger a shell parse error ("unmatched '") before intent is called.
#
# Workaround — wrap the whole prompt in double quotes:
#   i "what's the status of nginx"         ← works
#   i "check if today's date is correct"   ← works
#   i what's the status of nginx           ← zsh: unmatched '
#
# This is a fundamental zsh tokenisation constraint; it cannot be
# fixed by an alias or shell function.
# ──────────────────────────────────────────────────────────────────────
alias i='noglob i'
alias intent='noglob intent'
`

// bashSnippet: bash's default is to leave unmatched globs literal,
// so prompts like `i is google's dns up?` already pass through. We
// only need to do anything for users who turned on `failglob`. The
// alias trick below works for both: `set -f` disables pathname
// expansion, the alias is expanded before globs, and `set +f` runs
// in a trap on RETURN to restore the previous state.
const bashSnippet = `# intent shell integration — generated by ` + "`i shell-init bash`" + `
# In default bash, unmatched globs (?, *, [...]) pass through literally,
# so this is mostly a no-op safety net. If you've enabled
# ` + "`shopt -s failglob`" + ` it becomes load-bearing — the alias disables
# pathname expansion before the prompt is parsed and re-enables it after.
#
# Add to ~/.bashrc:   eval "$(intent shell-init bash)"
alias i='set -f; _intent_unset_f i'
alias intent='set -f; _intent_unset_f intent'
_intent_unset_f() {
  local cmd=$1; shift
  command "$cmd" "$@"
  local rc=$?
  set +f
  return $rc
}
`

// fishSnippet: fish doesn't expand `?` at all (it's not a glob char),
// only `*` and `**`. Unmatched `*` is an error by default. fish has no
// equivalent of `noglob`, but we can `string escape` the args inside a
// wrapper function — wait, no, that's also too late, expansion happens
// at parse time.
//
// The honest fix in fish is to tell users to quote `*` if they need it
// in a prompt. We still print a function so users have a uniform
// integration story, and so any future fish-side fix has a place to
// live without changing the user's setup.
const fishSnippet = `# intent shell integration — generated by ` + "`i shell-init fish`" + `
# Note: fish does not expand ? (it's not a glob character in fish), so
# prompts like ` + "`i is google's dns up?`" + ` work without any setup.
# fish *does* expand * and **; if your prompt needs a literal * you'll
# still need to quote it: ` + "`i 'rename *.txt to *.md'`" + `.
#
# Add to ~/.config/fish/config.fish:
#   intent shell-init fish | source
function i --wraps=intent
    command i $argv
end
function intent
    command intent $argv
end
`
